events {}

http {

  upstream client_a {
    server client-a:3000;
  }

  upstream client_b {
    server client-b:8000;
  }

  server {
    listen 80;

    server_name client-a.example.com;

    location / {
      proxy_pass http://client_a;
    }
  }

  server {
    listen 80;

    server_name client-b.example.com;

    location / {
      proxy_pass http://client_b;
    }
  }
}
